#!/bin/bash
#---- project parameters
project_name=DemoApp01
project_version=0.0.1
main_class=core.App
JARS=
vendor_name="VENDORNAME"
author_name="Frédéric Delorme<frederic.delorme@merckgoup.com>"
#
#--- DO NOT CHANGE THE FOLLOWING LINES ---
#
main_class_array=($main_class)
num_main_classes=${#main_class_array[@]}
SRC=./src
LIBS=./libs
TARGET=./target
BUILD=${TARGET}/build
CLASSES=${TARGET}/classes
RESOURCES=${SRC}/main/resources
SOURCE_ENCODING="UTF-8"
SOURCE_VERSION="25"
JARS=libs/dependencies/
COMPILATION_OPTS="-Xlint:unchecked -Xlint:deprecation -parameters"
JAR_OPTS="-Xmx512m"
# add your test execution commands here
TEST_CLASSES=${TARGET}/test-classes
TEST_RESOURCES=${SRC}/test/resources
LIB_TEST=$LIBS/junit-platform-console-standalone-6.0.0.jar
# detect OS type to set the classpath separator
if [[ "$OSTYPE" == "linux"* ]]; then
  FS=":"
else
  FS=";"
fi
# define colors
RED='\033[0;31m'
GREEN='\033[0;32m'
BLUE='\033[0;34m'
NC='\033[0m'
#---- process buid
GIT_COMMIT_ID=$(git rev-parse HEAD)
JAVA_BUILD=$(java --version | head -1 | cut -f2 -d' ')
#---- check JAVA version before SDKMAN
REQUIRED_JAVA_VERSION=$SOURCE_VERSION
JAVA_BIN=$(command -v java 2>/dev/null)
JAVA_VERSION_DETECTED=$($JAVA_BIN -version 2>&1 | awk -F '[\"_]' '/version/ {print $2}' | cut -d'.' -f1)
if [ -z "$JAVA_BIN" ] || [ "$JAVA_VERSION_DETECTED" != "$REQUIRED_JAVA_VERSION" ]; then
  echo -e "${RED}Java n'est pas installé. Tentative d'installation de Java $REQUIRED_JAVA_VERSION avec SDKMAN.${NC}"
  # Ensure the `sdk` command is available by sourcing SDKMAN init if installed
  if [ -z "$(command -v sdk 2>/dev/null)" ] && [ -s "$HOME/.sdkman/bin/sdkman-init.sh" ]; then
    # shellcheck source=/dev/null
    source "$HOME/.sdkman/bin/sdkman-init.sh"  
    if [ -f .sdkmanrc ]; then
      echo "Install SDKMAN environment"
      sdk env install
      sdk env use
      echo "done."
    fi
  fi
else
  echo -e "${GREEN}Java détecté: version $JAVA_VERSION_DETECTED${NC}"
fi
#---- check SDKMAN

# Prepare Build
rm -vrf target/
find $SRC/main/java $RESOURCES -name "*.java"
mkdir -vp ${TARGET}/{classes,build/libs}
# Compile sources
javac ${COMPILATION_OPTS} -cp libs/  $(find $SRC/main/java $RESOURCES -name "*.java") -d ${CLASSES}
# create MANIFEST file
cp -vr $RESOURCES/* $CLASSES
echo "build jar..."
for app in "${main_class_array[@]}"
do
  if [ $num_main_classes -eq 1 ]; then
    jar_name="${project_name}-${project_version}.jar"
  else
    jar_name="${project_name}-$app-${project_version}.jar"
  fi
  mkdir -p $TARGET/META-INF
  echo ">> for ${project_name}.$app..."
  echo """
Manifest-Version: ${project_name}
Main-Class: ${app}
Class-Path: ${JARS}
Created-By: ${JAVA_BUILD}
Implementation-Title: ${project_name}
Implementation-Version: ${project_version}-build_${GIT_COMMIT_ID:0:12}
Implementation-Vendor: ${vendor_name}
Implementation-Author: ${author_name}
""" >>target/META-INF/MANIFEST.MF
  jar cvfe target/build/${jar_name} $app -C target/classes .
  # create run script
  echo "create run script ${project_name}.sh ..."
  rm -f ${project_name}.sh 
  echo """#!/bin/bash
java -cp ${JARS// /,} -jar ${TARGET}/build/${jar_name} \$@
""" >${project_name}.sh
  chmod +x ${project_name}.sh
  echo "done."
done
if( [ "$1" == "test" ] ); then
  echo "Run tests..."

  echo -e "|_ ${BLUE}6. Execute tests${NC}..."
  echo "> from : ${SRC}/test"
  echo "> to   : ${TARGET}/test-classes"
  mkdir -p ${TARGET}/test-classes
  echo "copy test resources"
  cp -r ./$RESOURCES/* $TEST_CLASSES
  cp -r ./$TEST_RESOURCES/* $TEST_CLASSES
  echo "compile test classes"
  #list test sources
  find ${SRC}/main -name '*.java' >${TARGET}/sources.lst
  find ${SRC}/test -name '*.java' >${TARGET}/test-sources.lst
  javac -source $SOURCE_VERSION -encoding $SOURCE_ENCODING $COMPILATION_OPTS -cp ".${FS}$LIB_TEST${FS}${EXTERNAL_JARS}" -d $TEST_CLASSES @${TARGET}/sources.lst @${TARGET}/test-sources.lst
  echo "execute tests through JUnit"
  java $JAR_OPTS -jar $LIB_TEST execute -cp "${EXTERNAL_JARS}${FS}${CLASSES}${FS}${TEST_CLASSES}${FS}." --scan-class-path
  echo -e "   |_ ${GREEN}done$NC"
  echo "- execute tests through JUnit ${SRC}/test." >>${TARGET}/build.log
fi

if( [ "$1" == "run" ] ); then
  echo "Run the generated JAR(s)..."
  for app in "${main_class_array[@]}"
  do
    if [ $num_main_classes -eq 1 ]; then
      jar_name="${project_name}-${project_version}.jar"
    else
      jar_name="${project_name}-$app-${project_version}.jar"
    fi
    echo ">> run JAR ${jar_name} ..."
    shift 1
    java $RUN_OPT -jar ${TARGET}/build/${jar_name} $@
    echo "done."
  done
fi
